GrupoFournier/GrupoFournier/ProyectoBase/Controllers/Sys/UsuarioController.cs
using Cross.Common;
using Entities;
using Fwk.Crypto;
using Fwk.Session;
using Logic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Logic.GrupoFournier;

namespace PresentacionGrupoFournier.Controllers.Sys
{
    public class UsuarioController : BaseController<Usuario, UsuarioLogic>
    {

        #region Actions
        // GET: Usuario
        /// <summary>
        /// Vista de grilla para usuarios
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //var usuario = logic.GetAllActivos();
            var usuario = logic.GetUsuarioRolInferior();
            return View(usuario);
        }

        /// <summary>
        /// Vista de creacion/edicion de usuario
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Save(long? id)
        {
            Usuario usuario;
            //Si id es null estoy creando un nuevo usuario
            if (id == null)
            {
                usuario = new Usuario();
                usuario.Habilitado = true;
                usuario.Password = GeneratePassword();
                ViewBag.Title = "Crear Usuario";
                ViewBag.isEditando = false;
            }
            else
            {
                ViewBag.Title = "Editar Usuario";
                usuario = logic.GetByID(id.Value);
                usuario.Password = Cryptography.Decrypt(usuario.Password);
                ViewBag.selectedddlRol = usuario.Rol.EntityID;
                ViewBag.selectedddlEmpresa = usuario.Empresa.EntityID;
                ViewBag.isEditando = true;

            }
            return View(usuario);
        }

        /// <summary>
        /// Guarda un usuario
        /// </summary>
        /// <param name="usuario"></param>
        /// <param name="ClienteID"></param>
        /// <param name="ClienteNombre"></param>
        /// <returns></returns>
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Save([Bind]Usuario usuario, long ddlRol, long? ddlEmpresa, bool? isMailCursoTerminado)
        {
            //Agrego el rol
            usuario.Rol = new Rol { EntityID = ddlRol };
            // -- Agrego Empresa
            usuario.Empresa = new Empresa { EntityID = ddlEmpresa.HasValue ? ddlEmpresa.Value : SessionManager.Get<Usuario>(Global.SessionsKeys.USER_SESSION).Empresa.EntityID };
            //indica si se le va a mandar un mail al usuario cada vez que un usuario de esa empresa finalice un curso
            usuario.IsMailCursoTerminado = isMailCursoTerminado.HasValue ? isMailCursoTerminado.Value : false;
            if (ModelState.IsValid)
            {
                // -- Encripto contrasena
                usuario.Password = Cryptography.Encrypt(usuario.Password);
                // Seteo activo
                usuario.Activo = true;
                //Si es un nuevo usuario
                if (usuario.EntityID == 0)
                {
                    //Seteo el nombre de uusario en minusculas
                    usuario.NombreUsuario = usuario.NombreUsuario.ToLower();
                    //Seteo si esta editando
                    ViewBag.isEditando = false;
                    //Seteo titulo
                    ViewBag.Title = "Crear Usuario";

                    if (usuario.NombreUsuario.Contains(" "))
                    {
                        //Seteo error
                        ModelState.AddModelError("NombreUsuario", "El nombre de usuario no puede contener espacios en blanco");
                    }
                    else if (logic.Add(usuario) == -99)//Si hay error al agregar
                    {
                        //Seteo selected rol
                        ViewBag.selectedddlRol = ddlRol;
                        //Seteo selected empresa
                        ViewBag.selectedddlEmpresa = ddlEmpresa;
                        //Seteo error
                        ModelState.AddModelError("NombreUsuario", "El nombre de usuario ya se encuentra en uso");
                    }
                    else
                    {
                        MailLogic mlog = new MailLogic();
                        mlog.EnviarEmail(usuario.EntityID, string.Empty, Global.MailsTypes.REGISTRO);
                        //Redirecciono al index si no hubo error
                        TempData["SaveSuccess"] = "Se guardó usuario correctamente";
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    //Actualizo usuario
                    logic.Update(usuario);
                    //Redirecciono al index si no hubo error
                    TempData["SaveSuccess"] = "Se guardó usuario correctamente";
                    return RedirectToAction("Index");
                }
            }
            if (usuario.EntityID == 0)
            {
                ViewBag.isEditando = false;
            }
            else
            {
                ViewBag.isEditando = true;
            }
            return View(usuario);


        }

        /// <summary>
        /// Vista para cambiar contrasena
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult ChangePassword(long? id, bool isEmpresa)
        {
            ViewBag.isEmpresa = isEmpresa;
            //Cambia el pass para el usuario que se encuentra logueado
            if (id == null)
            {
                // -- Obtengo usuario de sesion
                Usuario user = SessionManager.Get<Usuario>(Global.SessionsKeys.USER_SESSION);
                // -- Seteo que edito el actual
                ViewBag.isCurrentUser = true;
                // -- Retorno vista
                return View(user);
            }
            else
            {
                // -- Obtengo usuario por id
                Usuario user = logic.GetByID(id.Value);
                // -- Desencripto password
                user.Password = Cryptography.Decrypt(user.Password);
                // -- Genero nueva contrasena
                string newPassword = GeneratePassword();
                // -- Asigno nueva contrasena
                user.NewPassword = newPassword;
                // -- Asigno nueva contrasena
                user.NewPasswordRepeat = newPassword;
                // -- Seteo que no se edita el usuario actual
                ViewBag.isCurrentUser = false;
                // -- Retorno vista
                return View(user);
            }
        }

        /// <summary>
        /// Cambia la contraseña de un usuario
        /// </summary>
        /// <param name="usuario"></param>
        /// <returns></returns>
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult ChangePassword([Bind]Usuario usuario, bool isCurrentUser)
        {
            if (!usuario.NewPassword.Equals(usuario.NewPasswordRepeat))
            {
                ModelState.AddModelError("NewPassword", "Las contraseñas deben coincidir");
                ViewBag.isCurrentUser = isCurrentUser;
                return View(usuario);
            }
            if (logic.ChangePassword(usuario.EntityID, usuario.NewPassword, usuario.Password))
            {
                MailLogic mlog = new MailLogic();
                mlog.EnviarEmail(usuario.EntityID, usuario.NewPassword, Global.MailsTypes.CAMBIO_CONTRASEÑA);
                TempData["SaveSuccess"] = "Se cambió la contraseña correctamente";
                if (isCurrentUser)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            ViewBag.isCurrentUser = isCurrentUser;
            ModelState.AddModelError("Password", "La contraseña actual ingresada no es correcta");

            return View(usuario);
        }

        /// <summary>
        /// Vista de usuarios para empresa logueada
        /// </summary>
        /// <returns></returns>
        public ActionResult IndexEmpresa()
        {
            // -- Obtengo usuario logueado
            var usuarioLogueado = SessionManager.Get<Usuario>(Global.SessionsKeys.USER_SESSION);
            // -- Recupero usuarios por empresa
            var usuarios = logic.GetByEmpresa(usuarioLogueado.Empresa.EntityID);
            // -- Devuelvo vilsta
            return View(usuarios);
        }


        /// <summary>
        /// Vista de creacion/edicion de usuario
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult SaveUsuarioEmpresa(long? id)
        {
            Usuario usuario;
            //Si id es null estoy creando un nuevo usuario
            if (id == null)
            {
                usuario = new Usuario();
                usuario.Habilitado = true;
                usuario.Password = GeneratePassword();
                ViewBag.Title = "Crear Usuario";
                ViewBag.isEditando = false;
            }
            else
            {
                ViewBag.Title = "Editar Usuario";
                usuario = logic.GetByID(id.Value);
                usuario.Password = Cryptography.Decrypt(usuario.Password);
                ViewBag.selectedddlRol = usuario.Rol.EntityID;
                ViewBag.isEditando = true;

            }
            return View(usuario);
        }

        /// <summary>
        /// Guarda un usuario
        /// </summary>
        /// <param name="usuario"></param>
        /// <param name="ClienteID"></param>
        /// <param name="ClienteNombre"></param>
        /// <returns></returns>
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult SaveUsuarioEmpresa([Bind]Usuario usuario, long ddlRol, bool? isMailCursoTerminado)
        {

GrupoFournier/GrupoFournier/ProyectoBase/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

GrupoFournier/GrupoFournier/ProyectoBase/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

GrupoFournier/GrupoFournier/ProyectoBase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Grupo Fortius</title>
    @Styles.Render("~/bundles/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/bundles/Content/Select2")
    @Styles.Render("~/bundles/Content/TemaAdminLTE")
    @Styles.Render("~/bundles/Content/PNotifyStyle")

    @*<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">*@
</head>
<body class="hold-transition skin-black layout-boxed fixed">

    <div class="">
        <div class="wrapper">
            <header class="main-header" style="background-color:#696767">
                <!-- Logo -->
                @Html.Action("RenderLogoEmpresa", "Home")                
                <!-- Header Navbar: style can be found in header.less -->
                <nav class="navbar navbar-static-top" role="navigation">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <!-- User Account: style can be found in dropdown.less -->
                            @Html.Action("RenderDatosUsuario", "Home")
                        </ul>
                    </div>
                </nav>
            </header>
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    @Html.Action("RenderMenuRecursivo", "Home")
                </section>
                <!-- /.sidebar -->
            </aside>
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                @RenderBody()
            </div><!-- /.content-wrapper -->
            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    @*<b>Version</b> 2.3.0*@
                    @*@typeof(WebApiApplication).Assembly.GetName().Version*@
                </div>
                @*@Html.Action("RenderFooter", "Home")*@
                @*<strong>Copyright &copy; 2015 <a href="http://www.keepitsimple.com.ar/">Keep IT Simple</a>.</strong> All rights reserved.*@
            </footer>
        </div><!-- ./wrapper -->

    </div>
    @*@Html.Action("RenderUserRolesDDL", "Usuario")*@


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Scripts/TemaAdminLTE")
    @Scripts.Render("~/bundles/PNotify")
    @Scripts.Render("~/bundles/Scripts/JQuery-easy-overlay")
    @Scripts.Render("~/bundles/Scripts/Select2")
    <script>
        // --
        $.widget.bridge('uibutton', $.ui.button);
        // -- PNotify -> Style Swicher
        PNotify.prototype.options.styling = "bootstrap3";


        //-- Alertas cuando se guardo correctamente
        if ('@TempData.ContainsKey("SaveSuccess")' == 'True') {
            new PNotify({
                title: 'Se guardo correctamente',
                text: '@TempData["SaveSuccess"]',
                type: 'success',
                hide: true,
                delay: 8000
            });
        }
        else if ('@TempData.ContainsKey("Notice")' == 'True') {
            new PNotify({
                title: 'Atencion !',
                text: '@TempData["Notice"]',
                type: 'notice',
                hide: true,
                delay: 8000
            });
        }
        $(document).ready(function () {
            $('#buttonCambiarRol').click(function () {
                BloquearContenido();
                var rolID = $('#ComboRoles').val();
                $.ajax({
                    cache: false,
                    type: "GET",
                    url: '@Url.Action("CambiarRol", "Usuario")',
                    data: { "rolID": rolID },
                    success: function (data) {
                        DesbloquearContenido();
                        window.location.href = '@Url.Action("Index", "Home")';
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        DesbloquearContenido();
                        bootbox.alert("Error al cambiar de rol");
                    }
                });
            });
        });
    </script>
    @RenderSection("scripts", required: false)
    <!-- Alert handler -->
    <div class="container body-content">
        @*@{ Html.RenderPartial("_AlertsHandler"); }*@
    </div>
</body>
</html>