GrupoFournier/GrupoFournier/ProyectoBase/Controllers/GrupoFournier/CursoController.cs
using Cross.Common;
using Entities;
using Fwk.Session;
using Logic;
using ProyectoBase.Fwk.UI;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Logic.GrupoFournier;

namespace PresentacionGrupoFournier.Controllers
{
    public class CursoController : BaseController<Curso, CursoLogic>
    {
        #region CONST

        private const string ImagenesPath = "~/Imagenes/ImagenesCursos/";

        // -- El formato sería "curso" + curso.EntityID + extension
        // -- Ejemplo "curso1.jpg"
        private const string ImagenCursoPath = "curso{0}{1}";

        #endregion

        #region Logics

        CursoUsuarioLogic cursoUsuarioLogic;
        CursoUsuarioLogic CursoUsuarioLogic
        {
            get
            {
                if (cursoUsuarioLogic == null)
                {
                    cursoUsuarioLogic = new CursoUsuarioLogic();
                }
                return cursoUsuarioLogic;
            }
        }

        #endregion
        // GET: Curso
        /// <summary>
        /// Vista de lista de cursos
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            // -- Obtengo usuario logueado
            var usuarioLogueado = SessionManager.Get<Usuario>(Global.SessionsKeys.USER_SESSION);
            List<Curso> cursos = new List<Curso>();

            //Si el usuario es administrador del sitio o administrador recupero todos los cursos
            if (usuarioLogueado.Rol.EntityID == Convert.ToInt64(Global.Roles.ADMINISTRADOR) || usuarioLogueado.Rol.EntityID == Convert.ToInt64(Global.Roles.ADMINISTRADOR_SITIO))
            {
                cursos = logic.GetAllActivos();
            }
            else //Sino recupero los que se crearon en su empresa
            {
                cursos = logic.GetByCreadoEmpresa(usuarioLogueado.Empresa.EntityID);
            }

            return View(cursos);
        }

        /// <summary>
        /// Vista para crear o editar un curso
        /// </summary>
        /// <returns></returns>
        public ActionResult Save(long? id)
        {
            Curso curso;
            if (id == null)
            {
                // -- Seteo titulo
                ViewBag.Title = "Crear Curso";
                // Creo curso
                curso = new Curso();
            }
            else
            {
                // -- Seteo titulo
                ViewBag.Title = "Editar Curso";
                // -- Recupero curso
                curso = logic.GetByID(id.Value);
                // -- Asigno rol seleccionado
                ViewBag.selectedddlRol = curso.RolMinimo.EntityID;
            }
            return View(curso);
        }

        [HttpPost]
        public ActionResult Save([Bind] Curso curso, long ddlRol)
        {
            var imageFile = Request.Files["ImagenCurso"];

            if (curso.EntityID == 0)
            {
                // -- Obtengo archivos e imagenCurso
                var file = Request.Files["Archivo"];

                // -- Si carga archivos
                if (file != null && file.ContentLength > 0 && !string.IsNullOrEmpty(file.FileName))
                {
                    if (curso.Html != null && curso.Html != "")
                    {
                        FileInfo fileInfo = new FileInfo(file.FileName);
                        if (fileInfo.Extension.ToLower().Equals(".rar") || fileInfo.Extension.ToLower().Equals(".zip"))
                        {
                            curso.RolMinimo = new Rol { EntityID = ddlRol };
                            if (ModelState.IsValid)
                            {
                                string appPath = HttpContext.Server.MapPath("~/Cursos/");
                                // -- Agrego curso
                                logic.AddCurso(curso, appPath, file.InputStream);

                                TempData["SaveSuccess"] = "Se guardó curso correctamente";
                                return RedirectToAction("Index");
                            }
                        }
                        else
                        {
                            ModelState.AddModelError("Archivo", "Debe cargar un archivo del tipo zip o rar");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("NombreHTML", "Debe ingresar nombre HTML del curso");
                        ModelState.AddModelError("Archivo", "Vuelva a cargar el archivo deseado");
                        TempData["Notice"] = "Si carga archivos de curso debe ingresar nombre HTML";
                    }
                }
                // -- Si carga imagenCurso
                else if (imageFile != null && imageFile.ContentLength > 0 && !string.IsNullOrEmpty(imageFile.FileName))
                {
                    FileInfo fileInfo = new FileInfo(imageFile.FileName);
                    if (fileInfo.Extension.ToLower().Equals(".jpg") || fileInfo.Extension.ToLower().Equals(".jpeg") || fileInfo.Extension.ToLower().Equals(".gif") || fileInfo.Extension.ToLower().Equals(".png"))
                    {
                        curso.RolMinimo = new Rol { EntityID = ddlRol };
                        if (ModelState.IsValid)
                        {
                            string appPath = HttpContext.Server.MapPath(ImagenesPath);
                            // -- Agrego curso
                            logic.AddCurso(curso, appPath, imageFile.InputStream, fileInfo.Extension);

                            TempData["SaveSuccess"] = "Se guardó curso correctamente";
                            return RedirectToAction("Index");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("ImagenCurso", "Debe cargar una imagen del tipo .jpg .jpeg .gif o .png");
                    }
                }
                else
                {
                    curso.RolMinimo = new Rol { EntityID = ddlRol };
                    if (ModelState.IsValid)
                    {
                        logic.AddCurso(curso);

                        TempData["SaveSuccess"] = "Se guardó curso correctamente";
                        return RedirectToAction("Index");
                    }
                }
            }
            else
            {
                // -- Actualizo curso

                // -- Si tiene imagen
                if (imageFile != null && imageFile.ContentLength > 0 && !string.IsNullOrEmpty(imageFile.FileName))
                {
                    FileInfo fileInfo = new FileInfo(imageFile.FileName);
                    if (fileInfo.Extension.ToLower().Equals(".jpg") || fileInfo.Extension.ToLower().Equals(".jpeg") || fileInfo.Extension.ToLower().Equals(".gif") || fileInfo.Extension.ToLower().Equals(".png"))
                    {
                        curso.RolMinimo = new Rol { EntityID = ddlRol };
                        if (ModelState.IsValid)
                        {
                            string appPath = HttpContext.Server.MapPath(ImagenesPath);
                            // -- Agrego curso
                            logic.UpdateCurso(curso, appPath, imageFile.InputStream, fileInfo.Extension);

                            TempData["SaveSuccess"] = "Se guardó curso correctamente";
                            return RedirectToAction("Index");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("ImagenCurso", "Debe cargar una imagen del tipo .jpg .jpeg .gif o .png");
                    }
                }
                else
                {
                    if (curso.Imagen == null)
                    {
                        string[] extensions = { ".jpg", ".jpeg", ".png", ".gif" };
                        // -- Si existe la imagen la borro
                        string appPath = HttpContext.Server.MapPath(ImagenesPath);
                        string deletePath;
                        for (int i = 0; i <= 3; i++)
                        {
                            deletePath = appPath + string.Format(ImagenCursoPath, curso.EntityID, extensions[i]);
                            if (System.IO.File.Exists(deletePath))
                            {
                                System.IO.File.Delete(deletePath);
                            }
                        }
                    }

                    curso.RolMinimo = new Rol { EntityID = ddlRol };
                    logic.Update(curso);
                    TempData["SaveSuccess"] = "Se guardó curso correctamente";
                    return RedirectToAction("Index");
                }
            }

            // -- Seteo valor seleccionado para rol
            ViewBag.selectedddlRol = ddlRol;
            return View(curso);
        }

        /// <summary>
        /// Vista para cargar archivos de un curso
        /// </summary>
        /// <returns></returns>
        public ActionResult RecargarCurso(long? id)
        {
            Curso curso;
            // -- Seteo titulo
            ViewBag.Title = "Editar Curso - Recargar";
            // -- Recupero curso
            curso = logic.GetByID(id.Value);

            return View(curso);
        }

        /// <summary>
        /// Guarda archivos para el curso
        /// </summary>
        /// <param name="curso"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult RecargarCurso([Bind] Curso curso)
        {
            // -- Obtengo archivo
            var file = Request.Files["Archivo"];

            if (file != null && file.ContentLength > 0 && !string.IsNullOrEmpty(file.FileName))
            {
                FileInfo fileInfo = new FileInfo(file.FileName);

GrupoFournier/GrupoFournier/ProyectoBase/Views/Curso/HacerExamen.cshtml
@model Entities.Curso
@using MvcCustomHelpers.Razor
@{
    ViewBag.Title = "Examen";
}
<style>
    .formularioSimple .box {
        border-left: 1px solid #d2d6de;
        border-right: 1px solid #d2d6de;
    }

    .radiosOpcionesContainer {
        margin-left: 0;
        margin-right: 0;
        margin-top: 20px;
    }

        .radiosOpcionesContainer .row {
            margin-left: 10px;
            margin-right: 10px;
        }

    .buttonEnviarExamen {
        cursor: pointer;
    }

    .colorVerde{
        color : green;
        font-weight: bold;
    }
    .colorRojo{
        color: red;
        font-weight: bold;
    }
</style>
<div class="box box-info box-form">
    <div class="tituloVista row">
        <div class="col-md-12">
            <i class="fa fa-file-text-o fa-fw"></i>
            @ViewBag.Title
        </div>
    </div>
    <div class="formularioSimple">
        @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "examenForm" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.EntityID)

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                @foreach (var pregunta in Model.Preguntas.OrderBy(x => x.Orden))
                {
                    <div class="box box-danger box-form">
                        <div class="row">
                            <div class="col-md-12" style="font-size: 16px; font-weight: bold">
                                @pregunta.Titulo
                            </div>
                        </div>
                        <div class="row radiosOpcionesContainer" data-pregunta-id="@pregunta.EntityID">
                            @foreach (var opcion in pregunta.Opciones)
                            {
                                <div class="row">
                                    <div class="col-md-2">
                                        <input value="@opcion.EntityID" data-pregunta-id="@pregunta.EntityID" type="radio" name="radioPregunta-@pregunta.EntityID" />
                                    </div>
                                    <div class="col-md-10">
                                        <span class="textoOpcion">@opcion.Descripcion</span>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                }

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <a class="btn btn-success buttonEnviarExamen">
                            <i class="fa fa-floppy-o fa-fw"></i>Enviar
                        </a>
                    </div>
                </div>

            </div>
        }
    </div>
</div>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        var puedeHacerExamen = true;

        // -- Click en enviar examen
        $('.buttonEnviarExamen').click(function () {
            if(puedeHacerExamen)
            {
                var preguntasContestadas = true;
                // -- Por cada grupo de radios
                $('.radiosOpcionesContainer').each(function () {
                    // -- Obtengo el nombre del radio
                    var radioName = $(this).find('input').attr('name');
                    // -- Valido que este contestada la pregunta
                    if ($('input[name=' + radioName + ']:checked').val() == undefined) {
                        preguntasContestadas = false;
                    }
                });
                // -- Si todas estan contestadas
                if (preguntasContestadas) {
                    // -- Array de preguntas
                    var preguntas = [];
                    // -- Por cada grupo de radios
                    $('.radiosOpcionesContainer').each(function () {
                        var pregunta = new Object();
                        // -- Obtengo id de la pregunta
                        pregunta.EntityID = Number($(this).attr('data-pregunta-id'));
                        // -- Obtengo el nombre del radio
                        var radioName = $(this).find('input').attr('name');
                        // -- Valido que este contestada la pregunta
                        var radioElegido = Number($('input[name=' + radioName + ']:checked').val());
                        // -- Asigno la opcion elegida
                        pregunta.Opciones = [];
                        var opcion = new Object();
                        opcion.EntityID = radioElegido;
                        pregunta.Opciones.push(opcion);
                        // -- Agrego la pregunta
                        preguntas.push(pregunta);
                    });
                    // -- Llamo al ajax
                    // -- Llamo al ajax
                    BloquearContenido();
                    $.ajax({
                        cache: false,
                        type: "POST",
                        url: '@Url.Action("HacerExamen", "Curso")',
                        data: { "preguntas": preguntas, "cursoID" : @Model.EntityID },
                        success: function (data) {
                            DesbloquearContenido();
                            // -- Muestro mensaje
                            AlertSuccess(data.Mensaje, "Examen enviado");
                            // -- Pongo en rojo las contestadas(las que esten bien luego quedaran verdes)
                            $('input:checked').each(function(){
                                $(this).parent().parent().find('.textoOpcion').addClass('colorRojo');
                            });
                            for(var i=0; i<data.Preguntas.length; i++)
                            {
                                for(var j=0; j<data.Preguntas[i].Opciones.length; j++)
                                {
                                    if(data.Preguntas[i].Opciones[j].Correcta==true)
                                    {
                                        $('input[data-pregunta-id=' + data.Preguntas[i].EntityID + '][value='+ data.Preguntas[i].Opciones[j].EntityID +']').parent().parent().find('.textoOpcion').addClass('colorVerde').removeClass('colorRojo');
                                    }
                                }
                                
                            }
                            // -- Pongo en false para que no pueda hacer examen
                            puedeHacerExamen= false;
                            // -- Oculto boton enviar
                            $('.buttonEnviarExamen').hide();
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            DesbloquearContenido();
                            AlertError("Ha ocurrido un error y no se guardo el examen realizado", "Advertencia");
                        }
                    });


                }
                else {
                    AlertError('Debe contestar todas las preguntas', 'Alerta');
                }
            }
            else
            {
                AlertError('Ya realizo el examen', 'Alerta');
            }
        });
    </script>
}

GrupoFournier/GrupoFournier/ProyectoBase/Views/Curso/Index.cshtml
@model IEnumerable<Entities.Curso>
@using GridMvc.Html
@{
    ViewBag.Title = "Cursos";
}
@using MvcCustomHelpers.Razor

@helper CargarArchivosColumn(Entities.Curso curso)
{
    <a href="/Curso/RecargarCurso/@curso.EntityID" class="btn btn-xs btn-success"><i class="fa fa-fw fa-upload"></i>Subir Archivos</a>
}
@helper BorrarCurso(Entities.Curso curso)
{
    <button onclick="MostrarModalBorrarCurso(@curso.EntityID, '@curso.Descripcion')" class="btn btn-xs btn-danger"><i class="fa fa-fw fa-minus-circle"></i>Borrar</button>
}
@helper VerDiapositivas(long cursoID)
{
    <a href="/Diapositiva/Index?cursoID=@cursoID"><span class="btn btn-xs btn-success"><i class="fa fa-file-image-o fa-fw"></i>Diapositivas</span></a>
}
@helper VerCurso(Entities.Curso curso)
{
    Logic.DiapositivaLogic diapoLogic = new Logic.DiapositivaLogic();
    // -- Recupero diapositivas
    var diapositivas = diapoLogic.GetByCurso(curso.EntityID);
    if (diapositivas.Count > 0)
    {
        <a href="/Diapositiva/VerCurso/@curso.EntityID" class="btn btn-xs btn-warning"><i class="fa fa-fw fa-eye"></i>Ver Curso</a>
    }
    else
    {
        <a href="/Curso/VerCursoAdmin/@curso.EntityID" class="btn btn-xs btn-warning"><i class="fa fa-fw fa-eye"></i>Ver Curso</a>
    }
}
@Styles.Render("~/bundles/Content/GridMVC")
@Styles.Render("~/bundles/Content/dataTables")
<div class="box box-body">
    <div class="tituloVista row">
        <div class="col-md-12"><i class="fa fa-suitcase fa-fw"></i>@ViewBag.Title</div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p>
                @FormButtonsHelpers.FormButtonAdd("Save", "Curso")
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @Html.Grid(Model).Columns(columns =>
       {
           columns.Add(c => c.Nombre).Titled("Nombre");
           columns.Add(c => c.Descripcion).Titled("Descripcion");
           columns.Add(c => c.RolMinimo.Nombre).Titled("Rol Minimo");
           columns.Add().Encoded(false).Sanitized(false).RenderValueAs(r => GridHelpers.GridButtonEdit("Save", "Curso", r.EntityID)).SetWidth(30).Css("gridButtonColumn");
           columns.Add().Encoded(false).Sanitized(false).RenderValueAs(r => CargarArchivosColumn(r)).SetWidth(30).Css("gridButtonColumn");
           columns.Add().Encoded(false).Sanitized(false).RenderValueAs(r => GridHelpers.GridButton("Index", "Pregunta", "Preguntas", "fa fa-fw fa-question-circle", "btn btn-xs btn-danger", r.EntityID)).SetWidth(30).Css("gridButtonColumn");
           columns.Add().Encoded(false).Sanitized(false).RenderValueAs(r => VerCurso(r)).SetWidth(30).Css("gridButtonColumn");
           columns.Add().Encoded(false).Sanitized(false).RenderValueAs(r => VerDiapositivas(r.EntityID)).SetWidth(30).Css("gridButtonColumn");
           columns.Add().Encoded(false).Sanitized(false).RenderValueAs(r => BorrarCurso(r)).SetWidth(30).Css("gridButtonColumn");
       }).Sortable(false).WithMultipleFilters()
        </div>
    </div>
</div>

<div id="modalBorrarCurso" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Borrar Curso</h4>
            </div>
            <div class="modal-body" id="modal-body-borrar-curso">
                <p></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cerrar</button>
                <button type="button" id="buttonBorrarCurso" class="btn btn-danger">Borrar</button>
            </div>
        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/bundles/Scripts/GridMVC")
    @Scripts.Render("~/bundles/Scripts/dataTables")
    <script>
        var idCursoBorrar;

        $('#buttonBorrarCurso').click(function () {
            BloquearContenido();
            $.ajax({
                cache: false,
                type: "POST",
                url: '@Url.Action("BorrarCurso", "Curso")',
                data: { "cursoID": idCursoBorrar },
                success: function (data) {
                    DesbloquearContenido();
                    window.location.href = '/Curso/Index';
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    DesbloquearContenido();
                    AlertError("Ha ocurrido un error y no se guardo el examen realizado", "Advertencia");
                }
            });
        });

        // Muestra el modal para borrar curso
        function MostrarModalBorrarCurso(cursoID, descripcion) {
            idCursoBorrar = cursoID;
            $('#modal-body-borrar-curso').html('<p>Desea borrar el curso: "' + descripcion + '" ?</p>');
            $('#modalBorrarCurso').modal('show');
        }
    </script>
}

GrupoFournier/GrupoFournier/ProyectoBase/Views/Curso/MisCursos.cshtml
@model IEnumerable<Entities.Curso>
@using GridMvc.Html
@{
    ViewBag.Title = "Mis Cursos";
}
@using MvcCustomHelpers.Razor

@helper CargarArchivosColumn(Entities.Curso curso)
{
    <a href="/Curso/RecargarCurso/@curso.EntityID" class="btn btn-xs btn-success"><i class="fa fa-fw fa-upload"></i>Subir Archivos</a>
}

@helper VerCurso(Entities.Curso curso)
{
    Logic.DiapositivaLogic diapoLogic = new Logic.DiapositivaLogic();
    // -- Recupero diapositivas
    var diapositivas = diapoLogic.GetByCurso(curso.EntityID);
    if (diapositivas.Count > 0)
    {
        <a href="/Diapositiva/VerCurso/@curso.EntityID" class="btn btn-xs btn-success"><i class="fa fa-fw fa-eye"></i>Ver Curso</a>
    }
    else
    {
        <a href="/Curso/VerCurso/@curso.EntityID" class="btn btn-xs btn-success"><i class="fa fa-fw fa-eye"></i>Ver Curso</a>
    }
}

@Styles.Render("~/bundles/Content/GridMVC")
@Styles.Render("~/bundles/Content/dataTables")
<div class="box box-body">
    <div class="tituloVista row">
        <div class="col-md-12"><i class="fa fa-file-video-o fa-fw"></i>@ViewBag.Title</div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @Html.Grid(Model).Columns(columns =>
       {
           columns.Add(c => c.Nombre).Titled("Nombre");
           columns.Add(c => c.Descripcion).Titled("Descripcion");
           columns.Add().Encoded(false).Sanitized(false).RenderValueAs(r => VerCurso(r)).SetWidth(30).Css("gridButtonColumn");
           columns.Add().Encoded(false).Sanitized(false).RenderValueAs(r => GridHelpers.GridButton("HacerExamen", "Curso", "Examen", "fa fa-fw fa-file-text-o", "btn btn-xs btn-info", r.EntityID)).SetWidth(30).Css("gridButtonColumn");
           columns.Add().Encoded(false).Sanitized(false).RenderValueAs(r => GridHelpers.GridButton("MiCertificado", "Curso", "Certificado", "fa fa-fw fa-file-text-o", "btn btn-xs btn-info", r.EntityID)).SetWidth(30).Css("gridButtonColumn");
       }).Sortable(false).WithMultipleFilters()
        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/bundles/Scripts/GridMVC")
    @Scripts.Render("~/bundles/Scripts/dataTables")
    <script>
    </script>
}

GrupoFournier/GrupoFournier/ProyectoBase/Views/Curso/RecargarCurso.cshtml
@model Entities.Curso
@using MvcCustomHelpers.Razor
<style>
    .columnaTextBusqueda {
        padding-right: 0;
    }

    .columnaIconoBusqueda {
        padding-left: 0;
    }

    .formularioSimple .box {
        border-left: 1px solid #d2d6de;
        border-right: 1px solid #d2d6de;
    }
    .formularioSimple{
        max-width: 650px;
    }
</style>
@Styles.Render("~/bundles/Content/dataTables")
<div class="box box-info box-form">
    <div class="tituloVista row">
        <div class="col-md-12">
            <i class="fa fa-users fa-fw"></i>
            @ViewBag.Title
        </div>
    </div>
    <div class="formularioSimple">
        @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "cursoCreateForm", autocomplete = "false", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.EntityID)
            @Html.HiddenFor(model => model.Activo)
            @Html.HiddenFor(model => model.Cargado)
            @Html.HiddenFor(model => model.FechaAlta)
            @Html.HiddenFor(model => model.FilesFolder)
            @Html.HiddenFor(model => model.Html)

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                            @Html.EditorFor(x => x.Nombre, new { htmlAttributes = new { @class = "form-control" , @readonly= "true" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                        </div>
                </div>
                <div class="form-group">
                    @Html.Label("Archivo", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        <input type="file" name="Archivo" id="Archivo" class="form-control" accept=".zip" />
                        @Html.ValidationMessage("Archivo", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        @FormButtonsHelpers.FormButtonBackToList("Curso")
                        @FormButtonsHelpers.FormButtonPostSave()
                    </div>
                </div>
            </div>
        }
    </div>
</div>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/Scripts/dataTables")
    <script>

    </script>
}

GrupoFournier/GrupoFournier/ProyectoBase/Views/Curso/ReporteCursosUsuarios.cshtml
@model IEnumerable<Entities.CursoUsuario>
@using GridMvc.Html
@{
    ViewBag.Title = "Informe de cursos";
}
@using MvcCustomHelpers.Razor
@Styles.Render("~/Content/GridMVC")
@Styles.Render("~/Content/dataTables")
<style>
    .grid-mvc {
        width: 95%;
    }
</style>
<div class="box box-body">
    @using (Html.BeginForm("GenerarReporteCursosUsuarios", "Curso", FormMethod.Get, new { id = "GenerarReporteCursosUsuariosForm" }))
    {
        <div class="tituloVista row">
            <div class="col-md-12"><i class="fa fa-map-marker fa-fw"></i>@ViewBag.Title</div>
        </div>
        <div class="row">
            <div class="filtersContainer" style="">
                <div class="box box-warning box-solid box-filter">
                    <div class="box-header with-border">
                        <h3 class="box-title">Filtros</h3>
                        <div class="box-tools pull-right">
                            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        </div><!-- /.box-tools -->
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                        <div class="col-lg-3 col-md-6">
                            <div class="row">
                                <div class="col-md-4">Cursos:</div>
                                <div class="col-md-8">
                                    @DropDownListHelper.DropDownCursosDeEmpresa(Html, false)
                                </div>
                            </div>
                        </div>
                    </div><!-- /.box-body -->
                </div>
            </div>
        </div>
        @*<div class="row">
            <div class="col-md-12">
                @Html.Grid(Model).Columns(columns =>
       {
           columns.Add(c => c.Usuario.NombreCompleto).Titled("Usuario");
           columns.Add(c => c.EstadoCurso.Nombre).Titled("Estado");
           columns.Add(c => c.Nota).Titled("Nota");
       }).Sortable(false).WithMultipleFilters()
            </div>
        </div>*@
        <div class="row">
            <div class="col-lg-12 text-center">
                <button id="btnSubmit"
                        class="btn btn-success"
                        type="submit"
                        formaction="/Curso/GenerarReporteCursosUsuarios"
                        formtarget="_blank"
                        value="1">
                    <span class="fa fa-file-archive-o"></span> Generar Reporte
                </button>
            </div>
        </div>
    }
</div>
@section scripts{
    @Scripts.Render("~/Scripts/GridMVC")
    @Scripts.Render("~/Scripts/dataTables")
}

GrupoFournier/GrupoFournier/ProyectoBase/Views/Curso/VerCurso.cshtml
@{
    ViewBag.Title = "Curso";
}


@if ((bool)ViewBag.TieneAcceso)
{
    if ((bool)ViewBag.ExisteCurso)
    {
        <div>El curso se abrira en una nueva ventana</div>
        <script>
            window.open('@ViewBag.Url', '_blank');
        </script>
    }
    else
    {
        <div class="alerta">
            El curso no esta disponible, contacte al administrador.
        </div>
    }
}
else
{
    <div class="alerta">
        No esta autorizado para realizar la acción solicitada.
    </div>
}